// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Reset(): $CancellablePromise<$models.TimerSnapshot> {
    return $Call.ByID(894164148);
}

export function Snapshot(): $CancellablePromise<$models.TimerSnapshot> {
    return $Call.ByID(499355849);
}

export function Toggle(): $CancellablePromise<$models.TimerSnapshot> {
    return $Call.ByID(2035003321);
}
