package dreefile

import (
	"fmt"
	"path/filepath"
	"strings"
)

var Version = "dev"

const generatedMarkerPrefix = "// Code generated by dreego "

func generatedMarker(source string) string {
	source = filepath.ToSlash(source)
	return fmt.Sprintf("%s%s from %s. DO NOT EDIT. Run dreego generate to update.", generatedMarkerPrefix, Version, source)
}

func withGeneratedMarker(source, body string) string {
	return generatedMarker(source) + "\n\n" + body
}

func isGeneratedFile(content string) bool {
	line, _, _ := strings.Cut(content, "\n")
	return strings.HasPrefix(line, generatedMarkerPrefix) && strings.Contains(line, "DO NOT EDIT.")
}
