package dreefile

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeneratedMarkerFormat(t *testing.T) {
	Version = "v0.10.9"
	t.Cleanup(func() { Version = "dev" })
	got := generatedMarker("www/routes")
	want := "// Code generated by dreego v0.10.9 from www/routes. DO NOT EDIT. Run dreego generate to update."
	if got != want {
		t.Fatalf("generatedMarker() = %q, want %q", got, want)
	}
}

func TestGeneratedMarkerUsesSlashes(t *testing.T) {
	body := withGeneratedMarker(filepath.Join("www", "routes"), "package routes\n")
	first, _, _ := strings.Cut(body, "\n")
	if !strings.Contains(first, "from www/routes.") {
		t.Fatalf("marker must use forward slashes, got %q", first)
	}
}

func TestIsGeneratedFile(t *testing.T) {
	marked := withGeneratedMarker("www/routes", "package routes\n")
	if !isGeneratedFile(marked) {
		t.Fatal("a marked file must be recognized")
	}
	for _, content := range []string{
		"package routes\n",
		"// Code generated by hand. DO NOT EDIT.\npackage routes\n",
		"// Code generated by dreego from www/routes.\npackage x\n",
	} {
		if isGeneratedFile(content) {
			t.Fatalf("unmarked content must not be recognized:\n%s", content)
		}
	}
}

func TestApplyPlanRejectsUnmarkedDreeGo(t *testing.T) {
	root, path := relTempDreeGo(t, "www")
	if err := os.WriteFile(path, []byte("package www\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	plan := genPlan{
		files: map[string]string{path: withGeneratedMarker(root, "package www\n")},
		roots: []string{root},
	}
	err := applyPlan(plan, false)
	if err == nil {
		t.Fatal("expected applyPlan to reject an unmarked dree.go")
	}
	if !strings.Contains(err.Error(), "dree.go") || !strings.Contains(err.Error(), "generated by dreego") {
		t.Fatalf("diagnostic must name the file and the missing marker, got: %v", err)
	}
	content, readErr := os.ReadFile(path)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if string(content) != "package www\n" {
		t.Fatalf("unmarked file must not be modified, got:\n%s", content)
	}
}

func TestApplyPlanOverwritesMarkedDreeGo(t *testing.T) {
	root, path := relTempDreeGo(t, "www")
	if err := os.WriteFile(path, []byte(withGeneratedMarker(root, "package www // old\n")), 0o644); err != nil {
		t.Fatal(err)
	}
	want := withGeneratedMarker(root, "package www // new\n")
	plan := genPlan{files: map[string]string{path: want}, roots: []string{root}}
	if err := applyPlan(plan, false); err != nil {
		t.Fatalf("applyPlan: %v", err)
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != want {
		t.Fatalf("marked file must be overwritten, got:\n%s", content)
	}
}

func TestApplyPlanDeletesMarkedStaleDreeGo(t *testing.T) {
	root, path := relTempDreeGo(t, "stale")
	if err := os.WriteFile(path, []byte(withGeneratedMarker(root, "package stale\n")), 0o644); err != nil {
		t.Fatal(err)
	}
	plan := genPlan{files: map[string]string{}, roots: []string{root}}
	if err := applyPlan(plan, false); err != nil {
		t.Fatalf("applyPlan: %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("marked stale file must be removed, got: %v", err)
	}
}

func relTempDreeGo(t *testing.T, sub string) (string, string) {
	t.Helper()
	dir := filepath.Join(t.TempDir(), sub)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	rel, err := filepath.Rel(wd, dir)
	if err != nil {
		t.Fatal(err)
	}
	return rel, filepath.Join(rel, "dree.go")
}
