// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface TimerSnapshot {
    "remainingSeconds": number;
    "running": boolean;
    "status": string;
}
