version: '3'

tasks:
  default:
    cmds:
      - task --list

  generate:
    cmds:
      - dreego generate

  build:
    deps: [generate]
    cmds:
      - go build .

  run:
    deps: [generate]
    cmds:
      - go run .

  test:
    cmds:
      - go test ./...
